# Generated by Django 5.2.4 on 2025-07-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="segmented",
            field=models.ImageField(blank=True, null=True, upload_to="segmented/"),
        ),
    ]
