# Generated by Django 5.2.4 on 2025-07-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_patient_segmented"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="classified",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="detected",
        ),
    ]
