# Generated by Django 5.2.4 on 2025-07-31 11:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_patient_classified_remove_patient_detected"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="classified",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="detected",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mri_image",
            field=models.ImageField(upload_to=core.models.unique_mri_upload),
        ),
    ]
