# Generated by Django 5.2.4 on 2025-08-01 10:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_patient_classified_patient_detected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoTumorCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mri_image",
                    models.ImageField(upload_to=core.models.unique_mri_upload),
                ),
                ("detected", models.CharField(default="no", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TumorCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mri_image",
                    models.ImageField(upload_to=core.models.unique_mri_upload),
                ),
                ("detected", models.CharField(default="yes", max_length=20)),
                ("classified", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "segmented",
                    models.ImageField(blank=True, null=True, upload_to="segmented/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
