# Generated by Django 5.2.4 on 2025-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_patient_delete_notumorcase_delete_tumorcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="mri_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
