# Generated by Django 5.2.4 on 2025-08-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_patient_mri_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="tumor_area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tumor_center_x",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tumor_center_y",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
